# Generated by Django 6.0.6 on 2026-06-26 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_category_id_alter_event_id_alter_eventtype_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='event_images/default.jpg', upload_to='event_images/'),
        ),
    ]
